spring.application.name=DOP-Request-Form

spring.datasource.url=jdbc:postgresql://localhost:5432/dop_request_form
spring.datasource.username=aidanp.beattie
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
